Correct environment variable `mc` configuration
bitnami/bitnami-docker-minio-client pull request #6
Opened 2022-02-07 10:21 UTC by vvidovic-croz

This pull request contains an update to the README.md
with correct usage instructions and an example of usage
instructions when using environment variables to pass
the host, access key and access secret to the `mc` command.

Usage instructions for the MinIO(R) Client container contains
an incorrect (outdated?) setup for configuring environment variables.

Old:
- `MINIO_SERVER_HOST`
- `MINIO_SERVER_ACCESS_KEY`
- `MINIO_SERVER_SECRET_KEY`

New:
- `MC_HOST_<alias>`

Description and example changed to use the proper environment
variable as described on the:
- https://docs.min.io/docs/minio-client-complete-guide.html

Example tested locally to make sure it works as expected.

Signed-off-by: Vedran Vidovic <vvidovic@croz.net>

**Description of the change**

**Benefits**

**Possible drawbacks**

**Applicable issues**

**Additional information**

2022-02-08 19:22 UTC, marcosbc requested changes
Thanks for contributing!

I'm a bit confused by the mention of using "outdated" environment variable names. Note that this is not the official container image for minio-client, so there might be some discrepancies between environment variables (despite "official" envvars being supported in both).

In addition, please be aware that `MINIO_SERVER_` is the prefix supported for environment variables used by this container, which is also the one used by the Minio chart. See [`minio-client-env.sh`](https://github.com/bitnami/bitnami-docker-minio-client/blob/master/2022/debian-10/rootfs/opt/bitnami/scripts/minio-client-env.sh) for the full list of environment variables used in this image.

2022-02-08 19:22 UTC, marcosbc commented on README.md
> +$ docker run --rm -it --name minio-client \
Is any of `-i` or `-t` really needed for this example? My understanding is that it should only be necessary when running interactively, right?

2022-02-08 19:22 UTC, marcosbc commented on README.md
> +    mb myminio/my-bucket
Is the `myminio` change to `minio` necessary for this scenario? Just to understand the context of this particular change.

2022-02-09 06:49 UTC, vvidovic-croz commented on README.md
> +$ docker run --rm -it --name minio-client \
Right, I will remove it.

2022-02-09 06:51 UTC, vvidovic-croz commented on README.md
> +    mb myminio/my-bucket
I wanted to add something more unique. The bucket name must match the one in the environment variable `MC_HOST_<bucket_name>` and I thought that if we put just a `minio` it could be confusing to some people.

2022-02-09 07:11 UTC, vvidovic-croz commented on README.md
> +    mb myminio/my-bucket
About "outdated" - I was thinking about using `MINIO_SERVER_*` variables to configure the MinIO client.
I don't know if those worked in the previous versions (I guess they worked, otherwise these would not be used in the example). In the current version, the example test didn't work until I changed the `MINIO_SERVER_*` set of variables with the `MC_HOST_*` variable.

Hope I cleared this a bit.

2022-02-11 17:39 UTC, marcosbc requested changes
Hi @vvidovic-croz, I think I have found out what is happening and why the example is not working.

The environment variables were actually correct, but due to some misconfiguration, they were not being loaded. If you make this change, they should work fine:

```diff
--- a/2022/debian-10/rootfs/opt/bitnami/scripts/minio-client/entrypoint.sh
+++ b/2022/debian-10/rootfs/opt/bitnami/scripts/minio-client/entrypoint.sh
@@ -11,6 +11,9 @@ set -o pipefail
 . /opt/bitnami/scripts/libbitnami.sh
 . /opt/bitnami/scripts/liblog.sh

+# Load MinIO Client environment
+. /opt/bitnami/scripts/minio-client-env.sh
+
 print_welcome_page

 info "** Starting MinIO Client setup **"
```

Could you check if that solves your issues? If so, could you update the PR with those changes?

2022-02-14 08:51 UTC, vvidovic-croz commented
@marcosbc - I was not able to successfully create and list the bucket using the original example and the changed code.

What I did:
- created a new image including the proposed change (`docker build . -t minio-client:vv`)
- created a Docker network (as in the example)
- run the Docker MinIO server (as in the example)
- run the following commands using the newly build Docker MinIO client (configured as in the example):
```
$ docker run --rm --name minio-client --env MINIO_SERVER_HOST="minio" --env MINIO_SERVER_ACCESS_KEY="minio-access-key" --env MINIO_SERVER_SECRET_KEY="minio-secret-key" --network app-tier minio-client:vv mb minio/my-bucket
...
Bucket created successfully `minio/my-bucket`.

$ docker run --rm --name minio-client --env MINIO_SERVER_HOST="minio" --env MINIO_SERVER_ACCESS_KEY="minio-access-key" --env MINIO_SERVER_SECRET_KEY="minio-secret-key" --network app-tier minio-client:vv ls minio/my-bucket
...
mc: <ERROR> Unable to list folder. Requested file `/opt/bitnami/minio-client/minio` not found

$ docker run --rm --name minio-client --env MINIO_SERVER_HOST="minio" --env MINIO_SERVER_ACCESS_KEY="minio-access-key" --env MINIO_SERVER_SECRET_KEY="minio-secret-key" --network app-tier minio-client:vv ls minio/
...
mc: <ERROR> Unable to list folder. Requested file `/opt/bitnami/minio-client/minio` not found
```

I am not sure how could the original configuration find out the alias that needs to be used to access the MinIO server (in my new example, it is set to `myminio`).

I would suggest that you use the MinIO client environment variable (as in this PR) instead of custom server variables in the example. It works without any issues and is described in the [MinIO client documentation](https://docs.min.io/docs/minio-client-complete-guide.html):
```
export MC_HOST_<alias>=https://<Access Key>:<Secret Key>@<YOUR-S3-ENDPOINT>
```

2022-02-25 14:02 UTC, marcosbc commented
Hi @vvidovic-croz, after some investigation I have been able to identify the problem.

It seems like in this documentation we are referring to `MINIO_SERVER_ACCESS_KEY` and `MINIO_SERVER_SECRET_KEY` environment variables. However, for the `minio-client` container, these should be named `MINIO_CLIENT_ACCESS_KEY` and `MINIO_CLIENT_SECRET_KEY` for example.

That said, since those are the names for the environment variables in the `minio` container image, it could be worth adding an alias for those, which we are working on at this moment. We will let you know once the container images with the fix have been released.

2022-02-25 17:50 UTC, marcosbc commented
We just released minio-client [2022.2.23-debian-10-r3](https://github.com/bitnami/bitnami-docker-minio-client/commit/92df09511ee9f60cfb44d66e611908c37b30ae11) with the fix, so this PR should not be needed anymore. Let us know if you continue to find issues.

2022-03-18 01:33 UTC, closed without merging